#!/bin/bash
# Version: 3
#
# 2: Added "safe" for random
# 3: Added x<quantity> syntax
# 4: Added "alpha"

HELP="Generate password from /dev/{u,}random\n
\tUsage:\t$0 <length>(x<quantity>) ([readable/username/safe])\n\n
\t -h/--help:\tThis Text\n
\talpha:\t\tAlphanumeric string (a-zA-Z0-9)\n
\treadable:\tReplace -!@#$%^&*()_+~ and 0-9 with vocals\n
\tsafe:\t\tUse random instead of urandom\n
\tusername:\tSame as readable but with uppercase first letter only\n\n
Example:\n
\t$0 8x5 username"

#
if [ -z $1 ];then
  echo -e $HELP
  exit 1

elif [[ $1 == '-h' || $1 == '--help' ]];then
  echo -e $HELP
  exit 0
fi

if [[ "$1" =~ "x" ]];then
  N=$(echo $1 | cut -d 'x' -f 2)
  LENGTH=$(echo $1 | cut -d 'x' -f 1)
else
  N=1
  LENGTH=$1
fi

if [[ $# == 1 ]];then
  head /dev/urandom | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $LENGTH | head -n $N

elif [[ $# == 2 ]];then

  PW=$(head /dev/urandom | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $LENGTH | head -n $N)

  if [[ $2 == "username" ]];then

    # Convert special characters to vocals
    foo="$(echo $PW | sed 'y/-!@#$%^&*()_+~0123456789/aeiouaeiouaeioaeiouaeiou/')"
    # Uppercase first character for every password
    for word in $foo;do
      echo "$(tr '[:lower:]' '[:upper:]' <<< ${word:0:1})$(tr '[:upper:]' '[:lower:]' <<< ${word:1})"
    done

  elif [[ $2 == "alpha" ]];then
    for word in $PW;do
      echo $word | sed 'y/-!@#$%^&*()_+~/aeiouaeIOUAEIO/'
    done

  elif [[ $2 == "readable" ]];then
    for word in $PW;do
      echo $word | sed 'y/-!@#$%^&*()_+~0123456789/aeiouaeiouaeioaeiouaeiou/'
    done
    echo https://imgs.xkcd.com/comics/password_strength.png

  elif [[ $2 == "safe" ]];then
    PW=$(head -c $((3*$LENGTH)) /dev/random | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $LENGTH | head -n 1)
    nnn=0
    while (( $nnn < $N )); do
      while (( ${#PW} < $LENGTH )); do
        PW=${PW}$(head -c $((3*$LENGTH)) /dev/random | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $LENGTH | head -n 1)
        PW="${PW::$LENGTH}"
      done
      echo $PW
      PW=""
      nnn=$((nnn+1))
    done
    echo The crypto nut: https://imgs.xkcd.com/comics/privacy_opinions.png

  else
    echo -e $HELP
    exit 1

  fi

else
  echo -e $HELP
  exit 1
fi
