#!/bin/bash
# Version: 2
#
# 2: Added "safe" for random

HELP="Generate password from /dev/urandom\n
\tUsage:\t$0 <length> ([readable/username/safe])\n
\t\t$0 -h/--help"

#
if [ -z $1 ];then
  echo -e $HELP
  exit 1

elif [[ $1 == '-h' || $1 == '--help' ]];then
  echo -e $HELP
  exit 0

elif [[ $# == 1 ]];then
  head /dev/urandom | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $1 | head -n 1

elif [[ $# == 2 ]];then

  if [[ $2 == "username" ]];then
    foo="$(head /dev/urandom | tr -dc 'a-zA-Z-!@#$%^&*()_+~' | fold -w $1 | head -n 1 | sed 'y/-!@#$%^&*()_+~/aeiouaeiouaeio/')"
    foo="$(tr '[:lower:]' '[:upper:]' <<< ${foo:0:1})$(tr '[:upper:]' '[:lower:]' <<< ${foo:1})"
    echo $foo

  elif [[ $2 == "readable" ]];then
    head /dev/urandom | tr -dc 'a-zA-Z-!@#$%^&*()_+~' | fold -w $1 | head -n 1 | sed 'y/-!@#$%^&*()_+~/aeiouaeiouaeio/'
    echo https://imgs.xkcd.com/comics/password_strength.png

  elif [[ $2 == "safe" ]];then
    PW=$(head -c $((3*$1)) /dev/random | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $1 | head -n 1)
    while (( ${#PW} < $1 )); do
      PW=${PW}$(head -c $((3*$1)) /dev/random | tr -dc 'a-zA-Z0-9-!@#$%^&*()_+~' | fold -w $1 | head -n 1)
      PW="${PW::$1}"
    done
    echo $PW
    echo The crypto nut: https://imgs.xkcd.com/comics/privacy_opinions.png

  else
    echo -e $HELP
    exit 1

  fi

else
  echo -e $HELP
  exit 1
fi
