#!/bin/bash
# Version: 2

HELP='Moves a file but creates a symlink in place.\n\n
\tUsage: ./lnmv [file] [destination]'

if [ -z $1 ];then
    echo Error: Argument missing! See -h/--help
    exit 1
elif [[ $1 == '-h' || $1 == '--help' ]];then
    echo -e $HELP
    exit 0
fi

FILE="$1"
TARGET="$2"

mv "$FILE" "$TARGET"

# Ensure absolute path
FILE=$(realpath $FILE)
TARGET=$(realpath $TARGET)

# If moved to directory
if [[ -d $TARGET ]];then
  ln -s "$TARGET/$(basename $FILE)" "$FILE"
else
  ln -s "$TARGET" "$FILE"
fi
