#!/usr/bin/python3
# Version: 1

import sys, os

arguments = {}
arguments['-h, --help'] = 'Print help'

def strconv(string):

  if type(string) == list:
    string = " ".join(string)
  elif type(string) == str:
    pass
  else:
    raise RuntimeError( "Need a list or str, not %s!" % type(string) )

  translate = {}

  translate[' '] = '_'
  translate['ß'] = 'ss'
  translate['ä'] = 'ae'
  translate['ö'] = 'oe'
  translate['ü'] = 'ue'
  translate['Ä'] = 'Ae'
  translate['Ö'] = 'Oe'
  translate['Ü'] = 'Ue'
  translate['\''] = ''

  for key in translate:
    string = string.replace(key, translate[key])

  string = string.encode('utf-8','surrogateescape').decode('ascii', 'ignore')

  return string

if __name__ == "__main__":

  if any([1 if arg in sys.argv else 0 for arg in ['-h', '--help']]):

    name = os.path.basename(sys.argv[0])

    # Display help
    print("{program} converts a string with spaces and non-ascii into spaceless-ascii.\n".format(program=name))
    print("Usage: {program} \"<string>\"\n".format(program=name))

    for key in arguments:
      print("\t{}: {}".format(key, arguments[key]))

  elif len(sys.argv) == 1: pass

  else:
    print(strconv(sys.argv[1:]))
